// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"exchange-api/internal/midd"
	"exchange-api/internal/svc"
)

// RegisterHandlers 注册处理函数到指定的路由组中。
// 该函数主要用于初始化与用户注册相关的HTTP处理函数。
// 参数:
//
//	r *Routers - 路由器指针，用于注册处理函数。
//	serverCtx *svc.ServiceContext - 服务上下文指针，包含处理函数所需的上下文信息。
func RegisterHandlers(r *Routers, serverCtx *svc.ServiceContext) {
	order := NewOrderHandler(serverCtx)
	orderGroup := r.Group()
	orderGroup.Use(midd.Auth(serverCtx.Config.JWT.AccessSecret))
	orderGroup.Post("/order/history", order.History) // 历史委托订单 所有的订单
	orderGroup.Post("/order/current", order.Current) // 当前委托订单 状态 正在交易的状态
}
