// Code generated by goctl. DO NOT EDIT.
// Source: register.proto

package server

import (
	"grpc-common/market/types/rate"
	"market/internal/svc"
)

type ExchangeRateServer struct {
	svcCtx *svc.ServiceContext
	rate.UnimplementedExchangeRateServer
}

func NewExchangeRateServer(svcCtx *svc.ServiceContext) *ExchangeRateServer {
	return &ExchangeRateServer{
		svcCtx: svcCtx,
	}
}
