// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"market-api/internal/svc"
)

// RegisterHandlers 注册处理函数到指定的路由组中。
// 该函数主要用于初始化与用户注册相关的HTTP处理函数。
// 参数:
//
//	r *Routers - 路由器指针，用于注册处理函数。
//	serverCtx *svc.ServiceContext - 服务上下文指针，包含处理函数所需的上下文信息。
func RegisterHandlers(r *Routers, serverCtx *svc.ServiceContext) {
	// 创建一个新的处理函数实例。
	rate := NewExchangeRateHandler(serverCtx)
	rateGroup := r.Group()
	// 在路由组中注册处理函数，处理获取美元汇率的请求。
	rateGroup.Post("/exchange-rate/usd/:unit", rate.UsdRate)

	market := NewMarketHandler(serverCtx)
	marketGroup := r.Group()
	marketGroup.Post("/symbol-thumb-trend", market.SymbolThumbTrend)
	//marketGroup.Post("/symbol-thumb", market.SymbolThumb)
}
